testshapes – Tetran
testshapes Program
82 statements
Source File
Uses
iso_fortran_env
shapes
fields
random
Calls
Contents
Variables
F S line tee ell jay ess zee oh Ny Nx W H Ntest i xarr
Subroutines
check_x err
Variables
Type Attributes Name Initial
type(Field) :: F
type(Piece) :: S
type(Piece) :: line
type(Piece) :: tee
type(Piece) :: ell
type(Piece) :: jay
type(Piece) :: ess
type(Piece) :: zee
type(Piece) :: oh
integer, parameter :: Ny = 4
integer, parameter :: Nx = 4
integer, parameter :: W = 6
integer, parameter :: H = 10
integer, parameter :: Ntest = 100
integer :: i
integer :: xarr(Ntest)
Subroutines
subroutine check_x(x)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: x(:)
subroutine err(msg)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: msg
Call graph
testshapes calls random_init, check_x, err
random_init calls randint
check_x calls err