test_key – Tetran
test_key Program
26 statements
Source File
Uses
iso_fortran_env
iso_c_binding
cinter
errs
Calls
Contents
Variables
stdscr ic lastEsc
Variables
Type Attributes Name Initial
type(c_ptr) :: stdscr
integer(kind=c_int) :: ic
logical :: lastEsc = .false.
Call graph
test_key calls initscr, usleep, getch, endwin
initscr calls getmaxyx, f_initscr