test_menu – Tetran
test_menu Program
10 statements
Source File
Uses
iso_c_binding
cinter
menu
Calls
Contents
Variables
stdscr
Variables
Type Attributes Name Initial
type(c_ptr) :: stdscr
Call graph
test_menu calls initscr, title, endwin
initscr calls f_initscr, getmaxyx
title calls refresh, makeletter, cbreak, usleep, dissolve, noecho, timeout, getch, clear
makeletter calls draw_piece
dissolve calls randint, draw_piece
draw_piece calls mvaddch