AI_input – Tetran
AI_input Subroutine
9 statements
Source File
public subroutine AI_input(F, P)
Arguments
Type Intent Optional Attributes Name
class(Field), intent(in) :: F
class(Piece), intent(inout) :: P
Calls
Called by
Contents
None
Call graph
ai_input calls project_down, seek_deep, down_random
seek_deep calls move_random, height
height calls project_down
key_input calls ai_input
main calls key_input