dissolve – Tetran
dissolve Subroutine
15 statements
Source File
public recursive subroutine dissolve(P)
Arguments
Type Intent Optional Attributes Name
class(Piece), intent(inout) :: P
Calls
Called by
Contents
None
Call graph
dissolve calls randint, draw_piece
draw_piece calls mvaddch
title calls dissolve
tetran calls title
test_menu calls title