draw_piece – Tetran
draw_piece Subroutine
14 statements
Source File
public subroutine draw_piece(P)
Arguments
Type Intent Optional Attributes Name
class(Piece), intent(in) :: P
Calls
Called by
Contents
None
Call graph
draw_piece calls mvaddch
redraw calls draw_piece
dissolve calls draw_piece
makeletter calls draw_piece
title calls dissolve, makeletter
tetran calls title
test_menu calls title