key_input – Tetran
key_input Subroutine
67 statements
Source File
public subroutine key_input(F, P, NP)
Arguments
Type Intent Optional Attributes Name
class(Field), intent(inout) :: F
class(Piece), intent(inout) :: P
class(Piece), intent(inout), optional :: NP
Calls
Called by
Contents
None
Call graph
key_input calls flushinp, game_over, ai_input, getch
game_over calls endwin
ai_input calls project_down, seek_deep, down_random
seek_deep calls move_random, height
height calls project_down
main calls key_input