main – Tetran
main Subroutine
17 statements
Source File
subroutine main(F, P, NP)
time's up, move piece one step down. real(trate) is necessary for float time comparison!
Arguments
Type Intent Optional Attributes Name
class(Field) :: F
type(Piece) :: P
type(Piece) :: NP
Calls
Contents
None
Call graph
main calls freeze, key_input
freeze calls game_over
key_input calls getch, flushinp, ai_input, game_over
ai_input calls project_down, seek_deep, down_random
game_over calls endwin
seek_deep calls move_random, height
height calls project_down