random_init – Tetran
random_init Subroutine
19 statements
Source File
public subroutine random_init()
Arguments
None
Calls
Called by
Contents
None
Call graph
random_init calls randint
tetran calls random_init
testshapes calls random_init
randblock calls random_init