title – Tetran
title Subroutine
33 statements
Source File
public subroutine title(Fld)
Arguments
Type Intent Optional Attributes Name
class(Field), intent(in), optional :: Fld
Calls
Called by
Contents
None
Call graph
title calls makeletter, refresh, usleep, dissolve, noecho, timeout, getch, cbreak, clear
makeletter calls draw_piece
dissolve calls randint, draw_piece
draw_piece calls mvaddch
tetran calls title
test_menu calls title