# Gfortran >= 6 required for SUBMODULE
language: minimal
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6


matrix:
  include:
  - os: linux
    env: FC=gfortran-6
  - os: osx
    before_install:
    - brew update >/dev/null
    - brew upgrade cmake > /dev/null
    - brew install gcc >/dev/null

install:
  - cd build
  - cmake ..
  - cmake --build . --parallel

script: ctest --parallel --output-on-failure
