draw_screen – Tetran
draw_screen Subroutine
16 statements
Source File
subroutine draw_screen(F)
Arguments
Type Intent Optional Attributes Name
class(Field), intent(in) :: F
Calls
Called by
Contents
None
Call graph
draw_screen calls err, mvaddch
err calls endwin
redraw calls draw_screen