err – Tetran
err Subroutine
5 statements
Source File
subroutine err(msg)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: msg
Called by
Contents
None
Call graph
testshapes calls err, check_x
check_x calls err