flip – Tetran
flip Function
18 statements
Source File
public function flip(A, d)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: A(:,:)
integer, intent(in) :: d
Return Value integer
Called by
Contents
None
Call graph
fliplr calls flip
rot90 calls flip
flipud calls flip
horizflip calls fliplr
rotate calls rot90
vertflip calls flipud