randint – Tetran
randint Function
6 statements
Source File
public impure elemental function randint(lo, hi)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: lo
integer, intent(in) :: hi
Return Value integer
Called by
Contents
None
Call graph
cmd_parse calls randint
randomx calls randint
gen_type calls randint
dissolve calls randint
random_init calls randint
randblock calls randint, gen_type, random_init
tetran calls cmd_parse, random_init, title
title calls dissolve
testshapes calls random_init
init_block calls gen_type
test_menu calls title