std_real – Tetran
std_real Function
4 statements
Source File
public pure function std_real(A) result(std)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A(:)
Return Value real
Calls
Called by
Contents
None
Call graph
std_real calls mean
mean calls mean_real, mean_int
std calls std_real
randblock calls std