getmaxyx – Tetran
getmaxyx Interface
48 statements
Source File
interface
Called by
public subroutine getmaxyx(win, y, x) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: win
integer(kind=c_int) :: y
integer(kind=c_int) :: x
Call graph
initscr calls getmaxyx
tetran calls initscr
test_key calls initscr
test_menu calls initscr