std – Tetran
std Interface
3 statements
Source File
public interface std
Calls
Called by
Contents
Module Procedures
std_int std_real
Module Procedures
public pure function std_int(A) result(std)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: A(:)
Return Value real
public pure function std_real(A) result(std)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A(:)
Return Value real
Call graph
std calls std_int, std_real
std_int calls mean
std_real calls mean
mean calls mean_real, mean_int
randblock calls std