timeout – Tetran
timeout Interface
48 statements
Source File
interface
Called by
public subroutine timeout(delay) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: delay
Call graph
tetran calls timeout, title
title calls timeout
test_menu calls title