usleep – Tetran
usleep Interface
48 statements
Source File
interface
Called by
public subroutine usleep(time) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), value :: time
Call graph
title calls usleep
test_key calls usleep
tetran calls title
test_menu calls title