endwin – Tetran
endwin Interface
48 statements
Source File
interface
Called by
public subroutine endwin() bind(C)
Arguments
None
Call graph
test_menu calls endwin
err calls endwin
game_over calls endwin
draw_screen calls err
freeze calls game_over
key_input calls game_over
redraw calls draw_screen
main calls freeze, key_input