getch – Tetran
getch Interface
48 statements
Source File
interface
Called by
public function getch() result(ch) bind(C)
Arguments
None
Return Value integer(kind=c_int)
Call graph
title calls getch
key_input calls getch
test_key calls getch
tetran calls title
test_menu calls title
main calls key_input