mvaddch – Tetran
mvaddch Interface
48 statements
Source File
interface
Called by
public subroutine mvaddch(y, x, ch) bind(C, name="0")
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), value :: y
integer(kind=c_int), intent(in), value :: x
character(kind=c_char), intent(in), value :: ch
Call graph
draw_screen calls mvaddch
draw_piece calls mvaddch
redraw calls draw_screen, draw_piece
dissolve calls draw_piece
makeletter calls draw_piece
title calls dissolve, makeletter
tetran calls title
test_menu calls title