refresh – Tetran
refresh Interface
48 statements
Source File
interface
Called by
public subroutine refresh() bind(C, name="0")
Arguments
None
Call graph
title calls refresh
tetran calls title
test_menu calls title