image:
- Visual Studio 2017
- ubuntu1804

stack: python 3

environment:
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
  PY_DIR: C:\Python37-x64

clone_depth: 25

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
- cmd: set PATH=%MINGW_DIR%;%PATH%
- cmd: cinst -y ninja
- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends ninja-build > /dev/null

install:
- python -m pip install meson
- meson setup build

test_script: meson test -C build

artifacts:
- path: build/meson-logs/testlog.txt
  name: 'Meson test error log'
