motiontest – Tetran
motiontest Program
229 statements
Source File
Uses
iso_fortran_env
shapes
fields
Calls
Contents
Variables
W H failed
Functions
initial test_floor left_wall right_wall block_hit
Subroutines
print_piece print_block
Variables
Type Attributes Name Initial
integer, parameter :: W = 10
integer, parameter :: H = 10
logical :: failed = .false.
Functions
function initial(next) result(failed)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: next
Return Value logical
function test_floor(next) result(failed)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: next
Return Value logical
function left_wall(next) result(failed)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: next
Return Value logical
function right_wall(next) result(failed)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: next
Return Value logical
function block_hit(next) result(failed)
Arguments
Type Intent Optional Attributes Name
character, intent(in) :: next
Return Value logical
Subroutines
subroutine print_piece(P)
Arguments
Type Intent Optional Attributes Name
class(Piece), intent(in) :: P
subroutine print_block(B)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: B(:,:)
Call graph
motiontest calls test_floor, left_wall, initial, right_wall, block_hit
initial calls print_piece
print_piece calls print_block