randblock – Tetran
randblock Program
50 statements
Source File
Uses
iso_fortran_env
shapes
random
Calls
Contents
Variables
types Ntypes rtol ideal b e f g i n c u buf
Variables
Type Attributes Name Initial
character(len=*), parameter :: types = 'ITLJSZOD'
integer, parameter :: Ntypes = len(types)
real, parameter :: rtol = 0.01
real :: ideal
character, allocatable :: b(:)
real, allocatable :: e(:)
integer, allocatable :: f(:)
integer, allocatable :: g(:)
integer :: i
integer :: n
integer :: c(Ntypes)
integer :: u
character(len=16) :: buf
Call graph
randblock calls mean, gen_type, std, randint, random_init
mean calls mean_real, mean_int
gen_type calls randint
std calls std_int, std_real
random_init calls randint
std_int calls mean
std_real calls mean