tetran – Tetran
tetran Program
148 statements
Source File
Uses
menu
cinter
errs
blocks
shapes
fields
random
keys
iso_c_binding
Calls
Contents
Variables
stdscr trate difffact W H players i x0 debug update isAI F P NP
Subroutines
main redraw cmd_parse draw_screen draw_score
Variables
Type Attributes Name Initial
type(c_ptr) :: stdscr
integer :: trate
real :: difffact
integer :: W
integer :: H
integer :: players
integer :: i
integer :: x0(2)
logical :: debug
logical :: update = .false.
logical :: isAI(2) = [.false., .true.]
type(Field) :: F(2)
type(Piece) :: P(2)
type(Piece) :: NP(2)
Subroutines
subroutine main(F, P, NP)
time's up, move piece one step down. real(trate) is necessary for float time comparison!
Arguments
Type Intent Optional Attributes Name
class(Field) :: F
type(Piece) :: P
type(Piece) :: NP
subroutine redraw(F, P, NP)
Arguments
Type Intent Optional Attributes Name
class(Field), intent(in) :: F
class(Piece), intent(in) :: P
class(Piece), intent(in) :: NP
subroutine cmd_parse(W, H, difffact, players, debug)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: W
integer, intent(out) :: H
real, intent(out) :: difffact
integer, intent(out) :: players
logical, intent(out) :: debug
subroutine draw_screen(F)
Arguments
Type Intent Optional Attributes Name
class(Field), intent(in) :: F
subroutine draw_score(F)
Arguments
Type Intent Optional Attributes Name
class(Field), intent(in) :: F
Call graph
tetran calls title, cmd_parse, noecho, initscr, timeout, random_init, cbreak, clear
title calls noecho, timeout, cbreak, clear, makeletter, refresh, usleep, dissolve, getch
cmd_parse calls randint
initscr calls f_initscr, getmaxyx
random_init calls randint
makeletter calls draw_piece
dissolve calls randint, draw_piece
draw_piece calls mvaddch