name: ci_cmake
env:
  CI: true
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.F90"
      - "**/*.cmake"
      - "**/*.txt"
      - ".github/workflows/ci_cmake.yml"
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install packages
      run: |
        pip install ninja
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libncurses-dev

    - run: ctest -S setup.cmake -VV


  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install ninja
    - run: ctest -S setup.cmake -VV

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cinst -y ninja
    - run: ctest -S setup.cmake -VV
