name: ci_cmake
env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/*.txt"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install packages
      run: |
        pip install ninja
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libncurses-dev

    - run: ctest -S setup.cmake -VV


  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install ninja ncurses
    - run: ctest -S setup.cmake -VV


  windows:
    if: false  # waiting for MSYS2 on Actions, Tetran works fine with MSYS2
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - run: cinst -y ninja
    - run: ctest -S setup.cmake -VV
