name: ci_cmake
env:
  CI: true

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.F90"
      - "**/*.cmake"
      - "**/*.txt"
      - ".github/workflows/ci_cmake.yml"
  pull_request:
    paths:
      - "**/*.f90"
      - "**/*.F90"
      - "**/*.cmake"
      - "**/*.txt"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install packages
      run: |
        pip install cmake
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libncurses-dev

    - run: cmake -B build
      env:
        FC: gfortran

    - run: cmake --build build --parallel

    - run: ctest -V --parallel -E GUI
      working-directory: build

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - run: cinst -y ninja

    - run: cmake -B build -G Ninja
      env:
        FC: gfortran

    - run: cmake --build build --parallel

    - run: ctest -V --parallel -E GUI
      working-directory: build
