name: ci_cmake

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/*.txt"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libncurses-dev

    - run: cmake --preset=ninja
    - run: cmake --build build
    - run: ctest -E gui -V
      working-directory: build


  mac:
    needs: linux
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
    - uses: actions/checkout@v2

    - run: brew install ncurses

    - run: cmake --preset=gcc10
    - run: cmake --build build
    - run: ctest -E gui -V
      working-directory: build


  windows:
    needs: linux
    runs-on: windows-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-ncurses

    - uses: actions/checkout@v2

    - run: cmake --preset=ninja
    - run: cmake --build build
    - run: ctest -E gui -V
      working-directory: build
