name: ci_cmake

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux_macos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    env:
      FC: gfortran-12

    steps:

    - name: Install packages Linux
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends libncurses-dev

    - name: Install packages MacOS
      if: runner.os == 'macOS'
      run: brew install ncurses

    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default


  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v3

    - run: cmake --workflow --preset default
      env:
        CMAKE_GENERATOR: MinGW Makefiles
