name: ci_cmake

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/*.txt"
      - ".github/workflows/ci_cmake.yml"
  pull_request:
  release:
    types: published

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libncurses-dev

    - run: cmake --preset=make
    - run: cmake --build build
    - run: ctest -E gui -V
      working-directory: build

    - name: create package
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: blocktran-Linux.tar.gz
        path: build/package

    - name: Upload release exe
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/blocktran-Linux.tar.gz
        asset_name: blocktran-Linux.tar.gz
        asset_content_type: application/gzip

  mac:
    needs: linux
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
    - uses: actions/checkout@v2

    - run: brew install ncurses

    - run: cmake --preset=makegcc10
    - run: cmake --build build
    - run: ctest -E gui -V
      working-directory: build

    - name: create package
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: blocktran-Darwin.tar.gz
        path: build/package

    - name: Upload release exe
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/blocktran-Darwin.tar.gz
        asset_name: blocktran-Darwin.tar.gz
        asset_content_type: application/gzip

  windows:
    needs: linux
    runs-on: windows-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-ncurses

    - uses: actions/checkout@v2

    - run: cmake --preset=ninja
    - run: cmake --build build
    - run: ctest -E gui -V
      working-directory: build

    - name: create package
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: blocktran-Windows.zip
        path: build/package

    - name: Upload release exe
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/blocktran-Windows.zip
        asset_name: blocktran-Windows.zip
        asset_content_type: application/zip
