name: ci_cmake

env:
  CTEST_PARALLEL_LEVEL: 3

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.cmake"
      - "**/*.txt"
      - ".github/workflows/ci_cmake.yml"
  pull_request:
  release:
    types: published

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libncurses-dev ninja-build

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - name: create package
      if: github.event.action == 'published'
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: binary-archive
        path: build/package

    - name: Upload release
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/blocktran-linux.tar.zst
        asset_name: blocktran-linux.tar.zst
        asset_content_type: application/zip

  mac:
    needs: linux
    runs-on: macos-latest
    timeout-minutes: 15
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      FC: gfortran-11

    steps:
    - uses: actions/checkout@v2

    - run: brew install ncurses ninja

    - run: cmake --preset multi

    - run: cmake --build --preset debug
    - run: ctest --preset debug

    - run: cmake --build --preset release
    - run: ctest --preset release

    - name: create package
      if: github.event.action == 'published'
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: blocktran-darwin.tar.zst
        path: build/package

    - name: Upload release exe
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/blocktran-darwin.tar.zst
        asset_name: blocktran-darwin.tar.zst
        asset_content_type: application/zip

  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build -G "MinGW Makefiles"
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default

    - name: create package
      if: github.event.action == 'published'
      run: cpack --config build/CPackConfig.cmake

    - name: Upload artifact
      if: github.event.action == 'published'
      uses: actions/upload-artifact@v1
      with:
        name: blocktran-windows.tar.zst
        path: build/package

    - name: Upload release exe
      if: github.event.action == 'published'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/package/blocktran-windows.tar.zst
        asset_name: blocktran-windows.tar.zst
        asset_content_type: application/zip
