name: ci_cmake

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_cmake.yml"


jobs:

  linux_macos:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    name: ${{ matrix.os }} Ncurses-${{ matrix.ncurses }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ncurses: [true, false]

    env:
      FC: gfortran-12

    steps:

# Ncurses already installed on macOS and Linux runners
    # - name: Install packages Linux
    #   if: ${{ runner.os == 'Linux' &&  matrix.ncurses }}
    #   run: sudo apt install --no-install-recommends libncurses-dev

    - name: install X11 Linux
      if: ${{ runner.os == 'Linux' && !matrix.ncurses }}
      run: sudo apt install --no-install-recommends libxmu-dev libxpm-dev libxt-dev libxaw7-dev libx11-dev

    # - name: Install packages MacOS
    #   if: ${{ runner.os == 'macOS' &&  matrix.ncurses }}
    #   run: brew install ncurses

    - name: Install X11 macOS
      if: ${{ runner.os == 'macOS' && !matrix.ncurses }}
      run: brew install libxt libxaw libx11

    - uses: actions/checkout@v4

    - run: cmake -Bbuild -Dfind:BOOL=${{ matrix.ncurses }}

    - run: cmake --build build --parallel

    - run: ctest --preset default

  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - run: cmake --workflow --preset default
      env:
        CMAKE_GENERATOR: MinGW Makefiles
