name: ci_meson

on:
  push:
    paths:
      - "**/*.f90"
      - "**/meson.build"
      - ".github/workflows/ci_meson.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran ninja-build libncurses-dev

    - run: meson setup build
    - run: meson compile -C build

    - run: meson test -C build -v --suite nogui
