name: ci_meson

on:
  push:
    paths:
      - "**/*.f90"
      - "**/*.F90"
      - "**/*.build"
  pull_request:
    paths:
      - "**/*.f90"
      - "**/*.F90"
      - "**/*.build"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libncurses-dev
    - run: meson setup build
      env:
        FC: gfortran
    - run: ninja -C build
    - run: meson test -C build -v --suite nogui
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: brew install gcc
    - run: meson setup build
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: ninja -C build
    - run: meson test -C build -v --suite nogui
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Testlog
        path: build/meson-logs/testlog.txt

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: meson setup build
      env:
        FC: gfortran
    - run: ninja -C build
    - run: meson test -C build -v --suite nogui
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Windows_Meson_Testlog
        path: build/meson-logs/testlog.txt
